import LeanTraining.Semantics
import LeanTraining.Program

open LeanTraining.Semantics (small_step big_step State evalBExpr)
open LeanTraining.Program (Stmt VarID Value)

namespace LeanTraining.SemanticsTh

theorem small_step_skip (s: State) : small_step s Stmt.skip = (s, none) := by
  simp only [small_step]
  --rfl

theorem if_chained (s: State) (x y: VarID) (v: Value) :
(if y = x then v else if y = x then v else s y) = (if y = x then v else s y) := by
  grind

theorem small_step_assign (s: State) (x: VarID) (v: Value) : small_step s (Stmt.assign x v)
    = (fun y => if y == x then v else s y, none) := by
  rfl

theorem small_step_to_big_step (s s': State) (p p': Stmt) :
  small_step s p = (s', some p') → big_step s p = big_step s' p' := by
  intros h
  induction p generalizing s s' p'
  case skip =>
    rw [small_step_skip] at h
    grind
  case seq p1 p2 ih1 ih2 =>
    -- Proof generated by GitHub Copilot iteratively
    cases hsp1 : small_step s p1 with
    | mk s1 op1 =>
      cases op1 with
      | none =>
        simp [small_step, hsp1] at h
        rcases h with ⟨rfl, rfl⟩
        have hdone : big_step s p1 = s1 := by
          cases p1 with
          | skip =>
            simpa [small_step, big_step] using hsp1
          | seq q1 q2 =>
            have hsnd := congrArg Prod.snd hsp1
            simp [small_step] at hsnd
            have hfalse : False := by
              cases hq1 : (small_step s q1).snd <;> simp [hq1] at hsnd
            exact False.elim hfalse
          | assign x v =>
            simpa [small_step, big_step] using hsp1
          | ifThenElse b q1 q2 =>
            have hsnd := congrArg Prod.snd hsp1
            simp [small_step] at hsnd
            have hfalse : False := by
              cases he : evalBExpr s b <;> simp [he] at hsnd
            exact False.elim hfalse
        simp [big_step, hdone]
      | some p1' =>
        simp [small_step, hsp1] at h
        rcases h with ⟨rfl, rfl⟩
        have hp1 : big_step s p1 = big_step s1 p1' := by
          apply ih1
          simpa using hsp1
        simp [big_step, hp1]
  case assign x v =>
    simp [small_step] at h
  case ifThenElse b p1 p2 ih1 ih2 =>
    simp only [small_step] at h
    cases heval : evalBExpr s b with
    | false =>
      rw [heval] at h
      simp at h
      rcases h with ⟨h1, h2⟩
      rw [← h1]
      rw [← h2]
      simp [big_step, heval]
    | true =>
      rw [heval] at h
      simp at h
      rcases h with ⟨h1, h2⟩
      rw [← h1]
      rw [← h2]
      simp [big_step, heval]

end LeanTraining.SemanticsTh
